export const SITUACAO_CONVENIO = {
  ATIVO: 1,
  INATIVO: 2,
};

export const SITUACAO_CONVENIO_EMPRESA = SITUACAO_CONVENIO;
export const SITUACAO_CONVENIO_EMPRESA_FUNCIONARIO = SITUACAO_CONVENIO;

export const SITUACAO_FUNCIONARIO = {
  DESBLOQUEADO: 1,
  BLOQUEADO: 2,
};
