export const SITUACAO_ENTREGA = {
  RECUSADO_INICIAL: 1,
  PENDENTE: 2,
  ACEITO: 3,
  RECUSADO_ACEITO: 4,
  ATRIBUIDO: 5,
  EM_ROTA: 6,
  ENTREGUE: 7,
  CANCELADO_FUNCIONARIO: 8,
  DISTRIBUIDORA_NAO_ENCONTRADA: 9,
};

export const SITUACAO_PEDIDO = SITUACAO_ENTREGA;
