export const TIPO_FATURA = {
  ABERTA: 1,
  LANCAMENTO: 2,
  PENDENTE_PAGAMENTO: 3,
  RETIFICACAO: 4,
  FECHADO: 5,
};

export const SITUACAO_FATURA = {
  ABERTA: 1,
  PENDENTE_PAGAMENTO: 2,
  PAGO: 3,
  LIQUIDADA: 4,
};
