export const TIPO_ENTREGA_VALUE = {
  CRIADO: 1,
  ACEITO_DISTRIBUIDORA: 2,
  SEPARADO: 3,
  ENTREGA: 4,
  ENTREGUE: 5,
  CANCELADO: 6,
  DISTRIBUIDORA_NAO_ENCONTRADA: 7,
};

export const TIPO_ENTREGA = {
  PEDIDO_CRIADO: 'PEDIDO_CRIADO',
  PEDIDO_ACEITO_DISTRIBUIDORA: 'PEDIDO_ACEITO_DISTRIBUIDORA',
  PEDIDO_SEPARADO: 'PEDIDO_SEPARADO',
  PEDIDO_SAIU_PARA_ENTREGA: 'PEDIDO_SAIU_PARA_ENTREGA',
  PEDIDO_ENTREGUE: 'PEDIDO_ENTREGUE',
  PEDIDO_CANCELADO: 'PEDIDO_CANCELADO',
  DISTRIBUIDORA_NAO_ENCONTRADA: 'DISTRIBUIDORA_NAO_ENCONTRADA',
};

// export const TIPO_ENTREGA = [
//   {
//     VALUE: TIPO_ENTREGA_VALUE.CRIADO,
//     TEXT: 'PEDIDO_CRIADO',
//   },
//   {
//     VALUE: TIPO_ENTREGA_VALUE.ACEITO_DISTRIBUIDORA,
//     TEXT: 'PEDIDO_ACEITO_DISTRIBUIDORA',
//   },
//   {
//     VALUE: TIPO_ENTREGA_VALUE.SEPARADO,
//     TEXT: 'PEDIDO_SEPARADO',
//   },
//   {
//     VALUE: TIPO_ENTREGA_VALUE.ENTREGA,
//     TEXT: 'PEDIDO_SAIU_PARA_ENTREGA',
//   },
//   {
//     VALUE: TIPO_ENTREGA_VALUE.ENTREGA,
//     TEXT: 'PEDIDO_ENTREGUE',
//   },
//   {
//     VALUE: TIPO_ENTREGA_VALUE.CANCELADO,
//     TEXT: 'PEDIDO_CANCELADO',
//   },
// ];
