export const QUEUE_RABBITMQ = {
  STATUS_ENTREGA: 'STATUS_ENTREGA' as const,
  DECREMENTAR_SALDO_FUNCIONARIO: 'DECREMENTAR_SALDO_FUNCIONARIO' as const,
  REMESSA_DISTRIBUIDORA: 'REMESSA_DISTRIBUIDORA' as const,
  FATURA_EMPRESA: 'FATURA_EMPRESA' as const,
};

export const QUEUE_RABBITMQ_EXTERNAL = {
  NOTIFICAR_FCM: 'NOTIFICAR_FCM' as const,
};
